### ISSUE TITLE
relocate_image() and write()

### ISSUE THREAD

**Issue by haco20292** [erocarrera/pefile#108]
Hi, I found that relocate_image() changes raw data, but sometimes this raw data corresponds to a structure (For example, IMAGE_LOAD_CONFIG_DIRECTORY), so change of raw data will be discarded when write() is called. Can you handle this case? Thank you.

**Comment by smart-rabbit** [comment]
This problem is consequence of next:
you open pe with
```python
pe = pefile.PE("/path/sample.exe")    # by default this means fast_load = False
```
This parse and loads all the directories information to 'pe' object properties, like pe.DIRECTORY_ENTRY_EXPORT,pe.DIRECTORY_ENTRY_LOAD_CONFIG etc.
Than you rebase image:
```python
pe.relocate_image(0x406000)
```
This code correct  all VA(virtual addresses) to correspond new image base in image raw data (self.\_\_data\_\_)
Then you do next
```python
pe.write("/path/new_sample.exe")
```
And here is a nuance:
    'write()' method write all the directories information(!! that was parsed before relocation !!) from 'pe' object properties to raw data(self.\_\_data\_\_) and rewrite previously changed by relocation VAs(virtual addresses) and Voila! we have broken executable.

**How to bypass** this in appliance with current pefile implementation:
first you should open pe using 'fast_load=True' to avoid parsing and load all the directories information.
Than parse relocation directory(required to make relocation, see 'relocate_image' method implementation)
Than make relocation.
Than if required parse another directories, all directories will be parsed from raw data modified by previous relocation operation.
Explanation code:
```python
import pefile


# parse executable with 'fast_load=True' to avoid parsing and load all the directories information.
pe = pefile.PE("/path_to_exe/sample.exe",fast_load=True) 
# parse relocation directory
pe.parse_data_directories(directories=[ pefile.DIRECTORY_ENTRY['IMAGE_DIRECTORY_ENTRY_BASERELOC'])
# make relocation
pe.relocate_image(0x406000) 
# do what you want, if required parse another data directories 
# ...................................
```


**Possible issue solution** is to modify 'relocate_image()'  method. It should iterate through 'self.\_\_structures\_\_' (like 'write()' method do) and correct all VAs(virtual addresses) it meet.

**Comment by erocarrera** [comment]
Thanks for the PR fixing the issue! this should now be solved.
