### ISSUE TITLE
Remove future from dependencies

### ISSUE THREAD

**Issue by FantasqueX** [erocarrera/pefile#348]
I noticed pefile requires python version >= 3.6. As a result, future is not needed. Is it possible to remove future from dependencies?

**Comment by erocarrera** [comment]
That's quite possibly true! I will do so. Thanks for noticing.

**Comment by JasperJuergensen** [comment]
@erocarrera I noticed, that the last release was more than half a year ago. The change fixing this Issue here, is still not included in a release. In the meantime a CVE has been published for the future package (CVE-2022-40899). It probably does not effect pefile, but for anyone with a dependency vulnerability management it would be nice, if there would be a new release without the future package as dependency.

**Comment by themanifold** [comment]
Please publish this to pypi.
