### ISSUE TITLE
Pip update and new release

### ISSUE THREAD

**Issue by nyx0** [erocarrera/pefile#80]
Do you think you can update your [PIP page](https://pypi.python.org/pypi/pefile) 
and maybe release a new version of pefile (pefile-1.2.11 maybe).
When the version will be released, I would like to add a [formula](https://github.com/Homebrew/homebrew) if you agree.
Thank you,

**Comment by wzod** [comment]
Seconded.

If at all possible, could the releases page be updated with what is now in master (i.e. https://github.com/erocarrera/pefile/releases)?

Asking since the current version in master now resolves the issue with building/installing from source (having a static release would be very helpful).

Thanks!

**Comment by erocarrera** [comment]
Finally I managed to look into this issue. Apologies for the huge delay.

nyx0, feel free to add a formula. Thanks!
